require 'httparty'
require 'retriable'
require 'oauth2'
require 'nokogiri'

require 'salesforce-bulk-query/version'
require 'salesforce-bulk-query/client'
require 'salesforce-bulk-query/connection'
require 'salesforce-bulk-query/job'
require 'salesforce-bulk-query/errors'